# Exported from Render on 2025-06-25T04:17:46Z
services:
- type: web
  name: n8n-render
  runtime: docker
  repo: https://github.com/eborges-git/n8n-render
  plan: free
  envVars:
  - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
    sync: false
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
    sync: false
  - key: EXECUTIONS_DATA_PRUNE
    sync: false
  - key: DB_POSTGRESDB_PASSWORD
    sync: false
  - key: DB_POSTGRESDB_SCHEMA
    sync: false
  - key: DB_POSTGRESDB_USER
    sync: false
  - key: DB_POSTGRESDB_PORT
    sync: false
  - key: DB_POSTGRESDB_HOST
    sync: false
  - key: DB_POSTGRESDB_DATABASE
    sync: false
  - key: DB_TYPE
    sync: false
  - key: WEBHOOK_URL
    sync: false
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
